### PR TITLE
docs: update migration guide for Ts.ED dependencies

### PR DESCRIPTION
**Pull request by geekyharsh05**
## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Doc |  No          |

---

## Todos

- [x] Documentation

Solves #2369 

### Before
Screenshot 2024-10-04 at 10 27 36 PM

### After
Screenshot 2024-10-04 at 10 27 46 PM

### CODE REVIEW

**Comment by geekyharsh05** [comment]
@Romakita Can you please review this?

**Review by Romakita — APPROVED** [review]

**Comment by Romakita** [comment]
HI @geekyharsh05 

please just change the message commit by:

```ts
docs: update migration guide for Ts.ED dependencies
```

**Comment by geekyharsh05** [comment]
> HI @geekyharsh05 
> 
> please just change the message commit by:
> 
> ```ts
> docs: update migration guide for Ts.ED dependencies
> ```

Done

**Comment by Romakita** [comment]
No. You to rewrite your commit message using command line or your IDE. Not using the github ^^

fix will create a release. Here it’s just a doc improvment. I don’t to publish a release for that on npm.

**Comment by geekyharsh05** [comment]
@Romakita

**Pull request merged**
