### PR TITLE
feat(mongoose): Added DynamicRef decorator to support mongoose dynamic ref. Issue #567

### PR DESCRIPTION
**Pull request by ghmendonca**
feat(mongoose): Added DynamicRef decorator to support mongoose dynamic ref. Issue #567

## Informations

Type | Breaking change
Feature|No

****

## Description
Added a new decorator called DynamicRef to add dynamic refs via refPath property as documented in https://mongoosejs.com/docs/populate.html#dynamic-ref.

## Usage example

```
import {DynamicRef, Model, Enum} from "@tsed/mongoose";

@Model()
class MyModel {
    @DynamicRef('model') // The parameter here is the name of the field which will contain the name of the model for mongoose to populate
    entity: Ref<OtherModel | FooModel>

    @Enum(['OtherModel', 'FooModel'])
    model: string
}
```

Then, you can simply populate by the ref field:

```
const myModel = this.MyModel.findById('5d001194df1e1a18ac52bc86').populate('entity') // The entity field will come populated
```

## Todos

- [ ] Tests
- [X] Example
- [x] Documentation

I am not used to do tests and documentations, so I will leave them for someone else.

### CODE REVIEW

**Comment by ghmendonca** [comment]
One issue that I can already see is that mongoose throws an error when you try to populate the object, it says that the referenced model wasn't being registered. I couldn't manage to fix this through the decorators, so, the fix is simple, just inject the referenced model in your service and it will work.

**Comment by Romakita** [comment]
Thanks @ghmendonca for your PR.
Can you add documentation on mongoose.md about DynamicRef and explain with a note/warning section the possible issue about DynamicRef. Please :)

**Comment by Romakita** [comment]
Hello @ghmendonca, did you have time to finish this PR? 
Thanks for your jobs ;)

**Comment by ghmendonca** [comment]
Hello @Romakita, sorry the delay. Just committed the documentations. Also, I've being using this dynamic ref in the past weeks and it's working great :) hope everything is good now

**Comment by Romakita** [comment]
Thanks @ghmendonca 
Last point is the coverage test is down :). I haven't time to fix that right know. I try to find few minutes next week to fix that and merge it.

See you

**Comment by ghmendonca** [comment]
Great! Looking forward to see this PR being merged :)

See you

**Pull request merged**
