### PR TITLE
feat(bullmq): allow settings custom job ids from within job class

### PR DESCRIPTION
**Pull request by abenerd**
## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature| No          |

---

Make it easier for jobs to declare their own job ids. Giving them access to the payload and injected services. 
This also streamlines the job id creation when the job is dispatched in several places.

The added method is optional and therefore should not be a breaking change. 

```ts
import {JobController, JobMethods} from "@tsed/bullmq";

@JobController("example-with-custom-id")
class ExampleJobWithCustomId implements JobMethods {
  public handle(payload: {num: number}) {
    console.info("look at my awesome number: ", payload.num);
  }

  public jobId(payload: {num: number}): string {
    return `very realistic job id #${payload.num}`;
  }
}
```

## Todos

- [X] Tests
- [X] Coverage
- [X] Example
- [X] Documentation

### CODE REVIEW

**Review by Romakita — APPROVED** [review]

**Comment by abenerd** [comment]
Why'd you add the `WithJobId` interface again, this is not used anywhere and could lead to confusion with consumers. @Romakita

**Comment by Romakita** [comment]
@abenerd  I haven't added something ^^. I just rebased the branch to fixed the integration test... It haven't solved the problem. also the fail isn't related of your branch. I missed this issue from the last merge (using node v20). I work to fix that ;)

**Comment by abenerd** [comment]
Ah thanks for the clarification, I'll force push again then to remove the interface.

**Comment by Romakita** [comment]
@abenerd  Merged ;)

**Comment by abenerd** [comment]
Thanks!

**Pull request merged**
