### PR TITLE
fix(di): Remove constant serialization

### PR DESCRIPTION
**Pull request by RevanScript**
## Informations

Type | Breaking change
---|---
Fix | Yes/No

****

## Description
Serialization doesn't allow to pass functions to settings

### CODE REVIEW

**Comment by RevanScript** [comment]
ServerSettingsService tests failed. Will check when have time.

**Comment by Romakita** [comment]
@RevanScript I fixed the problem ;). Because we apply directly an Object.freeze on the obj, it freeze the object in ServerSettingsService also. I added a new  deepClone function in `@tsed/core` package to clone correctly an object with preserving function/classe.
You configuration should work correctly in case of `@tsed/graphql` ^^

See you

**Comment by Romakita** [comment]
v5.5.0

**Comment by RevanScript** [comment]
Awesome! Will test it in the evening. Thanks

**Pull request merged**
