### PR TITLE
Fix documentation for 404 ResourceNotFound

### PR DESCRIPTION
**Pull request by martin-papy**
## Information

Type | Breaking change
---|---
Doc | No

****

## Todos

- [x] Tests
- [x] Coverage
- [x] Example
- [x] Documentation

### CODE REVIEW

**Comment by martin-papy** [comment]
Fixed a type. Sorry :-)

**Review by Romakita — APPROVED** [review]

**Comment by Romakita** [comment]
Sorry I totally forgot this PR. Thanks for the fix ;)

**Pull request merged**
