### PR TITLE
Linguistic improvements

### PR DESCRIPTION
**Pull request by kpapadatos**
Typos or bad English syntax/grammar often negatively bias a user about a project's quality (usually correctly). This is a great project, and better English will help it acquire the popularity it deserves. I'm not an English professor, but I hope you'll find this proposal useful. Cheers!

### CODE REVIEW

**Comment by kpapadatos** [comment]
I can't propose a change to the repo's description so if you want you can edit it from
```txt
📐 A TypeScript Framework on top of Express. It provide a lot of decorators and guideline to write your code. 
```
to
```
📐 A TypeScript Framework on top of Express. It provides a lot of decorators and guidelines to write your code. 
```

**Comment by Romakita** [comment]
Thanks a lot @kpapadatos 
You right :)
If you have other suggestions, your welcome. Are you interested to review principal pages? 

See you
Romain

**Comment by kpapadatos** [comment]
> Thanks a lot @kpapadatos
> You right :)
> If you have other suggestions, your welcome. Are you interested to review principal pages?
> 
> Tell me ;)
> Romain

@Romakita Sure! What are principal pages? Maybe I'll take a look when I find some time.

**Comment by Romakita** [comment]
All pages are here : https://github.com/TypedProject/ts-express-decorators/tree/production/docs

The most important pages by priority are:
- getting-started.md
- configuration.md
- docs/*.md
- tutorials/*.md

If you have paypal account I can give you a gift for your help (from the opencontribution budget) ;)

Thanks for your help
Romain

**Pull request merged**
