### PR TITLE
chore(deps): update typeorm version

### PR DESCRIPTION
**Pull request by pirouet**
## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Chore | No          |

---

## Todos

- [ ] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

### CODE REVIEW

**Comment by pirouet** [comment]
Simple change to pull in the latest TypeORM version and pin to a specific (current latest) version

**Review by Romakita — COMMENTED** [review]
Ohhh ok thanks ^^

**Pull request merged**
