### PR TITLE
doc: some small fixes in the docs for oidc

### PR DESCRIPTION
**Pull request by stefanvanherwijnen**
## Information

Type | Breaking change
---|---
Doc | No

****

I spent some time trying to figure out how to setup oidc provider and only later found the TSed plugin. There were some small errors in the documentation and knowing how to get oidc-provider to log debug info also was essential to figure out why some things did not work.

I am thinking about writing a CLI plugin to bootstrap oidc-provider into a TSed app, because it is a PITA to setup oidc if you are not familiar with how everything works in OpenID/OAuth.

### CODE REVIEW

**Review by Romakita — APPROVED** [review]

**Comment by Romakita** [comment]
Hello @stefanvanherwijnen 
Thanks for the PR ;).

the cli plugin could be interesting ^^
Tell me if you need help ;)

**Comment by stefanvanherwijnen** [comment]
@Romakita
Is it possible to detect the PlatformApplication type (express or Koa) during runtime?
OIDC is currently not initialized correctly for koa: https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#mounting-oidc-provider

E.g. 404 routes are now handled twice using Koa, resulting in an internal server error

**Comment by Romakita** [comment]
You can retrieve the PlatformName by using the following code:
```
  @Constant("PLATFORM_NAME")
  platformName: string;
```

**Comment by Romakita** [comment]
@stefanvanherwijnen can you give me the changes to fix issue with oidc and koa?

**Comment by stefanvanherwijnen** [comment]
Sure, I am still testing it so I'll PR it when I'm sure it works correctly.

**Comment by Romakita** [comment]
Thanks a lot ;)

**Pull request merged**
